[package]
name = "open_cv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.91.3"
bytes = "1"
rand = "0.8.5"

